spring:
  application:
    name: nutrilog
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    user:
      password: none

  # Wsp√≥lne ustawienia JPA/Hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Podstawowa konfiguracja Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history

app:
  data:
    directory: ${user.dir}/data
    categories-file: categories.json
  repository:
    use-postgres: true

cors:
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: '*'
  allow-credentials: true

product:
  parsing:
    similarity-threshold: 0.85